name: build-docker-image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Get latest tag
        id: latesttag
        uses: actions/github-script@v5
        with:
          script: |
            const repo = context.repo;
            const tags = await github.rest.repos.listTags(repo);
            if (tags.data.length > 0) {
              return tags.data[0].name;
            } else {
              return '0.0.0';
            }
      - name: Set APP_VERSION
        run: echo APP_VERSION=${{ steps.latesttag.outputs.result }} >> $GITHUB_ENV

      - name: Handle beta version
        run: |
          if [[ "${{ env.APP_VERSION }}" == *"beta"* ]]; then
            echo APP_TAG=dev >> $GITHUB_ENV
          else
            echo APP_TAG=latest >> $GITHUB_ENV
          fi

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/386
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
          build-args:
            APP_NAME=lrcapi
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/lrcapi:${{ env.APP_VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/lrcapi:${{ env.APP_TAG }}
